apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devrole
  namespace: dev
rules:
- apiGroups: ["app"] # “” indicates the core API group
  resources: [“pods”]
  verbs: [“get”, "watch", “create”, “list”, "update"]