apiVersion: v1
kind: Pod
metadata:
 name: nginxpod
spec:
 containers:
  - name: nginx
    image: nginx
    volumeMounts:
     - name: vol1
       mountPath: /usr/share/nginx/html
 volumes:
  - name: vol1
    persistentVolumeClaim:
     claimName: mypvc
