apiVersion: v1
kind: Pod
metadata:
  name: web1
  labels:
   name: web1
spec:
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
     - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
           - minikube-m02
 containers:
  - name: web1
    image: nginx
    volumeMounts:
     - name: nginxstorage
       mountPath: /data
 volumes:
  - name: nginxstorage
    persistentVolumeClaim:
       claimName: coconut-pvc-cka01-str