apiVersion: v1
kind: Pod
metadata:
 name: web1
spec:
 containers:
  - name: web1
    image: nginx
    volumeMounts:
     - name:  hostvol
       mountPath: /usr/share/nginx/html
 volumes:
  - name: hostvol
    persistentVolumeClaim:
     claimName: pvc1

