apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv1
 #labels:
 # env: dev
spec:
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteMany
 persistentVolumeReclaimPolicy: Delete
 storageClassName: standard
 hostPath:
  path: /tmp/hostpath_pv
