apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orange-pvc
spec:
  resources:
    requests:
      storage: 5Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "orange-sc"
