apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc1
spec:
  accessModes:
   - ReadWriteMany
  #storageClassName: standard
  resources:
   requests:
    storage: 1Gi
  #selector: 
   #matchLabels:
    #env: dev
