apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pink-role-binding-cka24-arch
subjects:
- kind: ServiceAccount
  name: pink-sa-cka24-arch
  namespace: default
roleRef:
  kind: ClusterRole
  name: pink-role-cka24-arch
  apiGroup: rbac.authorization.k8s.io