apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
     - name: dbpassword
       valueFrom:
        secretKeyRef:
          name: dbpassword
          key: password
    volumeMounts:
        - name: pwdir
          mountPath: /home
  volumes:
   - name: pwdir
     secret:
      secretName: dbpassword
