apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
     - name: var1
       value: value1
     - name: var2
       valueFrom:
        secretKeyRef:
          name: mysecret
          key: user