apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webpod
  name: webpod
spec:
  containers:
  - image: nginx
    name: webpod
    command: [ "/bin/sh", "-c", "env" ]
    env:
     - name: username
       valueFrom:
        secretKeyRef:
         name: testsecret1
         key: username
     - name: password
       valueFrom:
         secretKeyRef:
          name: testsecret1
          key: password
     - name: yaml
       valueFrom:
        secretKeyRef:
         name: testsecret1
         key: newpodwithsecret.yaml
     - name: terraform
       valueFrom:
        configMapKeyRef:
         name: var.list
         key: provider 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
